--SQL Retail Sales Analysis-I

--CREATING A DATABASE
CREATE DATABASE SQL_PROJECT1
USE SQL_PROJECT1

--CREATING THE TABLE
CREATE TABLE Retail_Sales(
	Transaction_ID INT PRIMARY KEY,
	Sales_Date DATE,
	Sale_time TIME,
	Customer_ID INT,
	Gender VARCHAR(7),
	Age INT,
	Category VARCHAR(15),
	Quantity INT,
	Price_per_unit FLOAT,
	Cogs FLOAT,
	Total_Sales FLOAT
	);

--IMPORTED THE REQUIRD FILE IN THE CURRENT DATABASE

--COPYING THE TABLE VALUES INTO THE TABLE WHICH WE HAVE DEFINED EARLIER
INSERT INTO Retail_Sales
SELECT * 
FROM SQL_PROJECT1.dbo.RETAIL;

--VIEWING THE TABLE
SELECT*
FROM Retail_Sales;

--DATA CLEANING 

-- CHECKING FOR ANY NULL VALUES
SELECT*
FROM Retail_sales
WHERE
	Transaction_ID IS NULL
	OR
	Sales_date IS NULL
	OR 
	Sale_Time IS NULL
	OR 
	Customer_ID IS NULL
	OR 
	Gender IS NULL
	OR
	Age IS NULL
	OR 
	Category IS NULL
	OR 
	Quantity IS NULL
	OR 
	Price_per_unit IS NULL
	OR 
	Cogs IS NULL
	OR 
	Total_Sales IS NULL;

-- REMOVING RECORDS WITH NULL VALUES BY USING THE DELETE + IS NULL, TO ENSURE DATA ACCURACY AND INTEGRITY
DELETE FROM Retail_Sales
WHERE 
	Transaction_ID IS NULL
	OR
	Sales_date IS NULL
	OR 
	Sale_Time IS NULL
	OR 
	Customer_ID IS NULL
	OR 
	Gender IS NULL
	OR
	Age IS NULL
	OR 
	Category IS NULL
	OR 
	Quantity IS NULL
	OR 
	Price_per_unit IS NULL
	OR 
	Cogs IS NULL
	OR 
	Total_Sales IS NULL;

-- TABLE AFTER DATA CLEANING
SELECT*
FROM Retail_Sales;


-- DATA EXPLORATION 

--LOOKING FOR THE TOTAL NUMBER OF SALES MADE
SELECT COUNT(*) AS [Total Sales]
FROM Retail_Sales;

-- CHECKING THE TOTAL NUMBER OF DISTINCT CUSTOMERS
SELECT COUNT(DISTINCT(Customer_ID)) as [Total Customers]
FROM Retail_Sales;

--CHECKING THE NUMBER OF DISTINCT CATEGORIES
SELECT COUNT(DISTINCT(Category)) AS [Distinct Category]
FROM Retail_Sales;

-- CHECKING THE TYPES OF UNIQUE CATEGORIES
SELECT DISTINCT Category AS [Types of Categories]
FROM Retail_Sales;

--DATA ANALYSIS AND BUSINESS KEY PROBLEMS

-- CHECKING THE INFORMATIONS ABOUT THE CUSTOMERS WHO MADE ANY ORDER ON 05-11-2022
SELECT*
FROM Retail_Sales
WHERE Sales_Date LIKE '2022-11-05';

-- CHECKING THE DATA FOR THE CETAGORY OF CLOTHING, HAVING QUANTITIES MORE THAN 4 AND IN THE YEAR OF 2022
SELECT*
FROM Retail_Sales
WHERE 
	Category = 'Clothing' 
	AND 
	Quantity >= 4
	AND 
	MONTH(Sales_Date) = 11
	AND
	YEAR(Sales_Date) = 2022;

-- CHECKING THE TOTAL SALES MADE BY EACH CATEGORY, TO FIGURE OUT WHICH CATEGORY IS MOST PROFITABLE
SELECT 
	Category, 
	SUM(Total_Sales) AS [Total Sales], 
	COUNT(Total_Sales) AS [Total Purchases]
FROM Retail_Sales
GROUP BY Category
ORDER BY SUM(Total_Sales);

-- CHECKING FOR THE AVERAGE AGE OF THE BEAUTY CATEGORY BUYERS
SELECT ROUND(AVG(Age),2) AS [Average Age of Beauty Category]
FROM Retail_Sales
WHERE Category LIKE 'Beauty';

-- CHECKING HOW MANY CUSTOMERS DO MAKE PURCHASE OF FMORE THAN 1000
SELECT*
FROM Retail_Sales
WHERE Total_Sales>1000;

-- CHECKING WHICH GENDER PURCHASES IN WHAT MANNER IN EACH CATEGORIES
SELECT
	Category,
	Gender,
	COUNT(*) AS [Total Transactions]
FROM Retail_Sales
GROUP BY 
	Category,
	Gender
ORDER BY 
	Category, 
	COUNT(*);

-- CHECKING THE MONTH OF EACH YEAR WHICH IS HAVING THE HIGHEST AVERAGE OF TOTAL SALES
SELECT*
FROM (
	SELECT 
		YEAR(Sales_Date) AS [Year],
		MONTH(Sales_Date) AS [Month Number],
		ROUND(AVG(Total_Sales),2) AS [Average Sale],
		RANK() OVER(
			PARTITION BY YEAR(Sales_Date) 
			ORDER BY AVG(Total_Sales) DESC
			) AS [Rank]
	FROM Retail_Sales
	GROUP BY 
		YEAR(Sales_Date),
		MONTH(Sales_Date)
	) AS T1
WHERE RANK=1;

-- CHECKING THE EXPENDITURES DONE BY THE TOP 5 BUYERS
SELECT TOP 5
	Customer_ID,
	SUM(Total_Sales) AS [Total Sales]
FROM Retail_Sales
GROUP BY Customer_ID
ORDER BY SUM(Total_Sales) DESC;

-- CHECKING TOTAL NUMBER OF UNQIUE CUSTOMERS EACH CATEGORY HAS
SELECT
	Category,
	COUNT(DISTINCT(Customer_ID)) AS [Unique Customers]
FROM Retail_Sales
GROUP BY Category
ORDER BY COUNT(DISTINCT(Customer_ID));

-- CHECKING WHICH SHIFT THORUGH OUT THE DAY HAS THE MOST TOTAL PURCHASES
WITH ShiftCTE AS (
	SELECT*,
	CASE 
		WHEN DATEPART(HOUR, Sale_Time) < 12 THEN 'Morning'
		WHEN DATEPART(HOUR, Sale_Time) BETWEEN 12 AND 17 THEN 'Afternoon'
		ELSE 'Evening'
	END AS [Shift]
	FROM Retail_Sales
	)
SELECT
	Shift,
	COUNT(*) AS [Total Purchases]
FROM ShiftCTE
GROUP BY Shift;

--END OF THE PROJECT--
